name: Build and Publish MyMvcApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Adjust the version as needed

    - name: Restore dependencies
      run: dotnet restore MyMvcApp.csproj

    - name: Build
      run: dotnet build MyMvcApp.csproj --configuration Release --no-restore

    - name: Publish to folder
      run: dotnet publish MyMvcApp.csproj --configuration Release --output \published\